### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by dbkaplun** [hjelmn/gcusbadapter_osx#1]

**Comment by hjelmn** [comment]
Sorry. Should have responded sooner. You can use this by doing the following:

1) Download the kernel extension from: https://github.com/hjelmn/gcusbadapter_osx/releases . There are two versions. One allows the use of native mode in dolphin (gcusbadapter_raw.kext) and the other (gcusbadapter.kext) makes the controller available for any application. The later requires you to configure the controller and has been tested with Dolphin, SixtyForce, and OpenEmu.

2) Install the kernel extension into /System/Library/Extensions . You can do this in the console by running (assuming the kext is in your Downloads folder):

```
sudo cp -R ~/Downloads/gcusbadapter.kext /System/Library/Extensions/ ; sudo chown -R root:wheel /System/Library/Extensions/gcusbadapter.kext
```

3) Turn off kext signature checking. This is required for 10.9 and higher since Apple refuses to allow kext signing for my kext since I do not make the hardware. Run:

```
sudo nvram boot-args=kext-dev-mode=1
```

You can re-enable kext signature checking by running:

```
sudo nvram -d boot-args
```

But that will disable the driver.
